name: 'Continuous Deployment'

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: setup QEMU
        uses: docker/setup-qemu-action@v1

      - name: setup docker buildx
        uses: docker/setup-buildx-action@v1

      - name: login to dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ivanauliaa/alta-agmc:latest

      - name: ssh ec2 and redeploy docker
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            docker stop alta-agmc-app-1
            docker rm alta-agmc-app-1
            docker pull ivanauliaa/alta-agmc:latest
            docker run -d \
            -p 5000:5000 \
            -e APP_PORT=5000 \
            -e APP_ENV=production \
            -e DB_USER=${{ secrets.DB_USER }} \
            -e DB_PASS=${{ secrets.DB_PASS }} \
            -e DB_HOST=${{ secrets.DB_HOST }} \
            -e DB_PORT=${{ secrets.DB_PORT }} \
            -e DB_NAME=${{ secrets.DB_NAME }} \
            -e ACCESS_TOKEN_SECRET=${{ secrets.ACCESS_TOKEN_SECRET }} \
            -e MONGO_USER=${{ secrets.MONGO_USER }} \
            -e MONGO_PASS=${{ secrets.MONGO_PASS }} \
            -e MONGO_HOST=${{ secrets.MONGO_HOST }} \
            -e MONGO_PORT=${{ secrets.MONGO_PORT }} \
            -e MONGO_NAME=${{ secrets.MONGO_NAME }} \
            --name alta-agmc-app-1 \
            ivanauliaa/alta-agmc:latest